{"uuid": "a5005f44-76a0-48ec-8a5c-633bbb58a189", "children": ["bede5d7b-6c0f-4d2b-9d95-82d98b5d9e08"], "befores": [{"name": "sff_module", "status": "broken", "statusDetails": {"message": "tests.emulation.base.EmulationError: Value -1280 out of range for word\n", "trace": "  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\ai_playground\\llama3\\.llama3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\cmis\\tests\\conftest.py\", line 46, in sff_module\n    module = SFFEmulatedModule(module_config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\cmis\\tests\\emulation\\sff.py\", line 17, in __init__\n    super().__init__(config)\n  File \"F:\\Repos\\cmis\\tests\\emulation\\base.py\", line 149, in __init__\n    self._initialize_memory_map()\n  File \"F:\\Repos\\cmis\\tests\\emulation\\sff.py\", line 65, in _initialize_memory_map\n    self.memory_map.write_word(0x02, self._encode_temperature(-5.0))  # Temp low alarm\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\Repos\\cmis\\tests\\emulation\\base.py\", line 120, in write_word\n    raise EmulationError(f\"Value {value} out of range for word\")\n"}, "start": 1761423755597, "stop": 1761423755597}], "start": 1761423755597, "stop": 1761423755617}