{"name": "test_fault_conditions", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.002 == 0.0", "trace": "tests\\test_sff_features.py:93: in test_fault_conditions\n    assert tx_power == 0.0\nE   assert 0.002 == 0.0"}, "description": "Test fault condition handling", "start": 1761425007330, "stop": 1761425007331, "uuid": "eb407afd-d3ae-4cee-a7a0-c603f4f5bb33", "historyId": "862015f9b56b8286729c59b46ffad626", "testCaseId": "862015f9b56b8286729c59b46ffad626", "fullName": "tests.test_sff_features#test_fault_conditions", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sff_features"}, {"name": "host", "value": "RoyGeeBiv"}, {"name": "thread", "value": "35100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sff_features"}], "titlePath": ["tests", "test_sff_features.py"]}