{"name": "test_invalid_memory_access", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'tests.emulation.base.EmulationError'>", "trace": "tests\\test_basic.py:31: in test_invalid_memory_access\n    with pytest.raises(EmulationError):\nE   Failed: DID NOT RAISE <class 'tests.emulation.base.EmulationError'>"}, "description": "Test handling of invalid memory access", "start": 1761423911032, "stop": 1761423911032, "uuid": "295fdef5-8a2e-44c7-9503-3541ed95a43f", "historyId": "0653c8307313b347af2cb59bbd4a769b", "testCaseId": "0653c8307313b347af2cb59bbd4a769b", "fullName": "tests.test_basic#test_invalid_memory_access", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_basic"}, {"name": "host", "value": "RoyGeeBiv"}, {"name": "thread", "value": "36056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_basic"}], "titlePath": ["tests", "test_basic.py"]}