{"name": "test_fault_conditions", "status": "broken", "statusDetails": {"message": "tests.emulation.base.EmulationError: Value -39 out of range for word", "trace": "tests\\test_sff_features.py:86: in test_fault_conditions\n    sff_module.simulate_fault('tx_fault', True)\ntests\\emulation\\sff.py:115: in simulate_fault\n    self.update_monitoring()\ntests\\emulation\\sff.py:75: in update_monitoring\n    self.memory_map.write_word(0x66, self._encode_power(self._tx_power_mw + power_variation))\ntests\\emulation\\base.py:125: in write_word\n    raise EmulationError(f\"Value {value} out of range for word\")\nE   tests.emulation.base.EmulationError: Value -39 out of range for word"}, "description": "Test fault condition handling", "start": 1761424926935, "stop": 1761424926935, "uuid": "b8e98353-e3b9-45e9-9674-de90b151ab96", "historyId": "862015f9b56b8286729c59b46ffad626", "testCaseId": "862015f9b56b8286729c59b46ffad626", "fullName": "tests.test_sff_features#test_fault_conditions", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sff_features"}, {"name": "host", "value": "RoyGeeBiv"}, {"name": "thread", "value": "57124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sff_features"}], "titlePath": ["tests", "test_sff_features.py"]}